#!/usr/bin/env bash

for file in gemfiles/* Gemfile; do
  echo Using $file
  rm $file.lock &> /dev/null
  export BUNDLE_GEMFILE=$file
  bundle install > /dev/null
  bundle exec rake test
  rm $file.lock &> /dev/null
  echo -e "\n\n"
done
