# frozen_string_literal: true

require 'active_support'

require_relative 'route_translator/extensions'
require_relative 'route_translator/translator'
require_relative 'route_translator/host'
require_relative 'route_translator/version'

module RouteTranslator
  extend RouteTranslator::Host

  TRANSLATABLE_SEGMENT = /^([-_a-zA-Z0-9]+)(\()?/

  DEFAULT_CONFIGURATION = {
    available_locales:                   [],
    disable_fallback:                    false,
    force_locale:                        false,
    generate_unlocalized_routes:         false,
    generate_unnamed_unlocalized_routes: false,
    hide_locale:                         false,
    host_locales:                        {},
    locale_param_key:                    :locale,
    locale_segment_proc:                 false
  }.freeze

  Configuration = Struct.new(*DEFAULT_CONFIGURATION.keys)

  class << self
    private

    def resolve_host_locale_config_conflicts
      @config.force_locale                        = false
      @config.generate_unlocalized_routes         = false
      @config.generate_unnamed_unlocalized_routes = false
      @config.hide_locale                         = true
    end

    def check_deprecations; end
  end

  module_function

  # Configures the routes generated by RouteTranslator.
  #
  # @yieldparam config [Configuration] the mutable RouteTranslator configuration
  # @return [Configuration] the current configuration
  def config
    @config ||= Configuration.new

    DEFAULT_CONFIGURATION.each do |option, value|
      @config[option] ||= value
    end

    if block_given?
      yield @config
      @available_locales = nil
    end

    resolve_host_locale_config_conflicts if @config.host_locales.present?
    check_deprecations

    @config
  end

  # Restores the default RouteTranslator configuration.
  #
  # @return [Configuration] the reset configuration
  def reset_config
    @config = nil
    @available_locales = nil

    config
  end

  # Returns the locales for which translated routes are generated.
  #
  # @return [Set<Symbol>] the configured locales, or all I18n locales
  def available_locales
    @available_locales ||= begin
      i18n_locales = I18n.available_locales.to_set(&:to_sym)
      configured_locales = config.available_locales

      locales = if configured_locales.empty?
                  i18n_locales
                else
                  configured_locales.to_set(&:to_sym) & i18n_locales
                end

      default_locale = I18n.default_locale.to_sym

      # Make sure the default locale is translated in last place to avoid
      # problems with wildcards when the default locale is omitted in paths.
      locales.delete(default_locale)
      locales.add(default_locale)
      locales.freeze
    end
  end

  # Returns the request parameter key used for the locale.
  #
  # @return [Symbol, String] the configured locale parameter key
  def locale_param_key
    config.locale_param_key
  end

  # Extracts an available locale from route parameters.
  #
  # @param params [#[]] route parameters
  # @return [Symbol, nil] the requested available locale
  def locale_from_params(params)
    locale = params[config.locale_param_key]&.to_sym
    locale if available_locales.include?(locale)
  end

  # Extracts an available locale from request parameters or its host.
  #
  # Request parameters take precedence over host-based locale configuration.
  #
  # @param request [ActionDispatch::Request] the incoming request
  # @return [Symbol, nil] the requested available locale
  def locale_from_request(request)
    locale_from_params(request.params) || Host.locale_from_host(request.host)
  end

  def deprecator
    @deprecator ||= ActiveSupport::Deprecation.new(RouteTranslator::VERSION, 'RouteTranslator')
  end
end
